sudo: required
language: node_js
node_js: "14"
install:
  - npm ci
cache:
  directories:
    - "$HOME/.npm"
# before_install:
  # - docker build -t beatsbyalif/pico-test -f ./front/DockerFile.dev ./front

script:
  # - docker run -e CI=true beatsbyalif/pico-test npm run test -- --coverage
  - echo "Hellooo"

deploy:
  provider: netlify
  site: $site_id
  auth: $auth_id
  edge: true # opt in to dpl v2
  on:
    branch: main